##encoding=UTF8

"""
from constant import state_abbr, month_name_map
"""

state_abbr = {
"Alaska": "AK",
"Alabama": "AL",
"Arkansas": "AR",
"Arizona": "AZ",
"California": "CA",
"Colorado": "CO",
"Connecticut": "CT",
"District of Columbia": "DC",
"Delaware": "DE",
"Florida": "FL",
"Georgia": "GA",
"Hawaii": "HI",
"Iowa": "IA",
"Idaho": "ID",
"Illinois": "IL",
"Indiana": "IN",
"Kansas": "KS",
"Kentucky": "KY",
"Louisiana": "LA",
"Massachusetts": "MA",
"Maryland": "MD",
"Maine": "ME",
"Michigan": "MI",
"Minnesota": "MN",
"Missouri": "MO",
"Mississippi": "MS",
"Montana": "MT",
"North Carolina": "NC",
"North Dakota": "ND",
"Nebraska": "NE",
"New Hampshire": "NH",
"New Jersey": "NJ",
"New Mexico": "NM",
"Nevada": "NV",
"New York": "NY",
"Ohio": "OH",
"Oklahoma": "OK",
"Oregon": "OR",
"Pennsylvania": "PA",
"Rhode Island": "RI",
"South Carolina": "SC",
"South Dakota": "SD",
"Tennessee": "TN",
"Texas": "TX",
"Utah": "UT",
"Virginia": "VA",
"Vermont": "VT",
"Washington": "WA",
"Wisconsin": "WI",
"West Virginia": "WV",
"Wyoming": "WY",
}

month_name_map = {
    1: "January", 2: "february", 3: "March", 4: "April",
    5: "May", 6: "June", 7: "July", 8: "August",
    9: "September", 10: "October", 11: "November", 12: "December",
    }   